routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function(){
	return redirect()->route('criteria.index');
});

Route::prefix('alternative')->name('alternative.')->group(function(){
	Route::get('', 'AlternativeController@index')->name('index');
	Route::get('create', 'AlternativeController@create')->name('create');
	Route::post('', 'AlternativeController@store')->name('store');
	Route::get('{alternative}', 'AlternativeController@show')->name('show');
	Route::put('{alternative}', 'AlternativeController@update')->name('update');
	Route::delete('{alternative}', 'AlternativeController@destroy')->name('destroy');
});

Route::prefix('criteria')->name('criteria.')->group(function(){
	Route::get('', 'CriteriaController@index')->name('index');
	Route::get('create', 'CriteriaController@create')->name('create');
	Route::post('', 'CriteriaController@store')->name('store');
	Route::get('{criteria}', 'CriteriaController@show')->name('show');
	Route::put('{criteria}', 'CriteriaController@update')->name('update');
	Route::delete('{criteria}', 'CriteriaController@destroy')->name('destroy');
});

Route::prefix('score')->name('score.')->group(function(){
	Route::get('', 'ScoreController@index')->name('index');
	Route::get('create', 'ScoreController@create')->name('create');
	Route::post('', 'ScoreController@store')->name('store');
	Route::get('{alternative}', 'ScoreController@show')->name('show');
	Route::put('{alternative}', 'ScoreController@update')->name('update');
	Route::delete('{alternative}', 'ScoreController@destroy')->name('destroy');
});

Route::prefix('scoring')->name('scoring.')->group(function(){
	Route::get('', 'ScoringController@index')->name('index');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard {!! auth()->user()->is_admin == 1 ? 'Admin' : 'User' !!}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('title','Home')

@section('body')

<h1>this is user page</h1>

@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>{{ config('app.name') }} | @yield('title')</title>
	<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap.min.css')}}">
	<link rel="icon" type="image/gif" href="{{ asset('img/logo.png') }}">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/custom.css') }}">
	<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

	<script src="{{ asset('js/vendor/jquery-3.3.1.min.js') }}"></script>
	<script src="{{ asset('js/vendor/popper.min.js') }}"></script>
	<script src="{{ asset('js/bootstrap.min.js') }}"></script>
	<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
</head>
<body>
	<nav class="main-menu">
		<ul>
			<li>
				<a href="{{ route('criteria.index') }}"><i class="fa fa-cus fa-2x"><img src="{{ asset('img/logo.png') }}" width="35"></i><span class="nav-text"><b>{{ config('app.name') }}</b></span></a>
			</li>
			<br>
			<li>
				<a href="{{ route('criteria.index') }}"><i class="fa fa-file fa-cus fa-2x"></i><span class="nav-text">Kriteria</span></a>
			</li>
			<li>
				<a href="{{ route('alternative.index') }}"><i class="fa fa-user fa-cus fa-2x"></i><span class="nav-text">Alternatif</span></a>
			</li>
			<li>
				<a href="{{ route('score.index') }}"><i class="fa fa-list fa-cus fa-2x"></i><span class="nav-text">Penilaian</span></a>
			</li>
			<li>
				<a href="{{ route('scoring.index') }}"><i class="fa fa-calculator fa-cus fa-2x"></i><span class="nav-text">Perhitungan</span></a>
			</li>
			<li>

			</li>
		</ul>
		<ul class="logout">
			<li>
				<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-power-off fa-cus fa-2x"></i><span class="nav-text">Logout</span></a>
				<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
			</li>
		</ul>
	</nav>
	<div class="area">
		<div class="container-fluild">
			@yield('content')
		</div>
	</div>
</body>
</html>