routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function(){
	return redirect()->route('criteria.index');
});

Route::prefix('alternative')->name('alternative.')->group(function(){
	Route::get('', 'AlternativeController@index')->name('index');
	Route::get('create', 'AlternativeController@create')->name('create');
	Route::post('', 'AlternativeController@store')->name('store');
	Route::get('{alternative}', 'AlternativeController@show')->name('show');
	Route::put('{alternative}', 'AlternativeController@update')->name('update');
	Route::delete('{alternative}', 'AlternativeController@destroy')->name('destroy');
});

Route::prefix('criteria')->name('criteria.')->group(function(){
	Route::get('', 'CriteriaController@index')->name('index');
	Route::get('create', 'CriteriaController@create')->name('create');
	Route::post('', 'CriteriaController@store')->name('store');
	Route::get('{criteria}', 'CriteriaController@show')->name('show');
	Route::put('{criteria}', 'CriteriaController@update')->name('update');
	Route::delete('{criteria}', 'CriteriaController@destroy')->name('destroy');
});

Route::prefix('score')->name('score.')->group(function(){
	Route::get('', 'ScoreController@index')->name('index');
	Route::get('create', 'ScoreController@create')->name('create');
	Route::post('', 'ScoreController@store')->name('store');
	Route::get('{alternative}', 'ScoreController@show')->name('show');
	Route::put('{alternative}', 'ScoreController@update')->name('update');
	Route::delete('{alternative}', 'ScoreController@destroy')->name('destroy');
});

Route::prefix('scoring')->name('scoring.')->group(function(){
	Route::get('', 'ScoringController@index')->name('index');
});

app/Criteria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Criteria extends Model
{
    protected $fillable = [
    	'name', 'weight',
    ];

    public function scores()
    {
    	return $this->hasMany('App\Score');
    }

}

app/Http/Controllers/CriteriaController.php
<?php

namespace App\Http\Controllers;

use App\Criteria;
use Illuminate\Http\Request;

class CriteriaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // return view('criteria.index')->with([
        //     'criterias' => Criteria::orWhere('name','LIKE','%'.request('q').'%')->orWhere('weight','LIKE','%'.request('q').'%')->orderBy('id','DESC')->paginate(10)->appends(['q'=>request('q')]),
        // ]);

        return view('criteria.index')->with([
            'criterias' => Criteria::orWhere('name','LIKE','%'.request('q').'%')->orWhere('weight','LIKE','%'.request('q').'%')->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('criteria.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'weight' => 'required|integer|max:5',
        ]);

        Criteria::create([
            'name' => $request->name,
            'weight' => $request->weight,
        ]);

        return redirect()->route('criteria.index')->with('info','Kriteria berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Criteria  $criteria
     * @return \Illuminate\Http\Response
     */
    public function show(Criteria $criteria)
    {
        return view('criteria.show')->with('criteria',$criteria);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Criteria  $criteria
     * @return \Illuminate\Http\Response
     */
    public function edit(Criteria $criteria)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Criteria  $criteria
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Criteria $criteria)
    {
        $this->validate($request, [
            'name' => 'required',
            'weight' => 'required|integer|max:5',
        ]);

        $criteria->update([
            'name' => $request->name,
            'weight' => $request->weight,
        ]);

        return redirect()->route('criteria.index')->with('info','Kriteria berhasil diperbaharui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Criteria  $criteria
     * @return \Illuminate\Http\Response
     */
    public function destroy(Criteria $criteria)
    {
        $criteria->delete();

        return redirect()->route('criteria.index')->with('info','Kriteria berhasil dihapus');
    }
}

resources/views/criteria/create.blade.php
@extends('layout')

@section('title','Tambah Kriteria')

@section('content')
	<div class="container">
		<div class="card">
			<form action="{{ route('criteria.store') }}" method="post">
				@csrf
				<div class="card-header">
					<h1 class="card-title">Tambah Kriteria</h1>
				</div>
				<div class="card-body">
					<div class="form-group">
						<label>Nama</label>
						<input type="text" class="form-control" name="name" placeholder="Nama" required>
						@if($errors->has('name'))
							<p class="alert alert-warning">{{ $errors->first('name') }}</p>
						@endif
					</div>
					<div class="form-group">
						<label>Bobot</label>
						<input type="number" class="form-control" name="weight" placeholder="Nilai Bobot ( 1 - 5 )" required>
						@if($errors->has('weight'))
							<p class="alert alert-warning">{{ $errors->first('weight') }}</p>
						@endif
					</div>
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-outline-primary pull-right">Simpan</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/criteria/index.blade.php
@extends('layout')

@section('title','Kriteria')

@section('content')
	<div class="card">
		<div class="card-header">
			<h1 class="card-title">Data Kriteria</h1>
			<form action="{{ route('criteria.index') }}" method="GET">
				<div class="input-group">
					<input type="search" class="form-control" placeholder="Cari data kriteria..." name="q" value="{{ request('q') }}">
					<div class="input-group-append">
						<button type="submit" class="btn btn-outline-secondary"><i class="fa fa-search"></i></button>
						&nbsp
						<a href="{{ route('criteria.create') }}" class="btn btn-outline-primary"><i class="fa fa-plus"></i></a>
					</div>
				</div>
			</form>
		</div>
		<div class="card-body">
			@if(session()->has('info'))
				<p class="alert alert-success">{{ session()->get('info') }}</p>
			@endif
			<div class="table-responsive">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th width="1%">#</th>
							<th>Nama</th>
							<th>Bobot</th>
							<th width="5%">Aksi</th>
						</tr>
					</thead>
					<tbody>
						@foreach($criterias as $key => $criteria)
							<tr>
								<td class="text-right">{{ $key+1 }}</td>
								<td>{{ $criteria->name }}</td>
								<td>{{ $criteria->weight }}</td>
								<td>
									<div class="btn-group">
										<a href="{{ route('criteria.show',$criteria->id) }}" class="btn btn-outline-success"><i class="fa fa-eye"></i></a>
										&nbsp
										<form id="delete" action="{{ route('criteria.destroy',$criteria->id)}}" method="post">
										@csrf
										@method('delete')
										<button type="submit" href="#" class="btn btn-outline-danger" onclick="return confirm('Hapus kriteria {{ $criteria->name }}')"><i class="fa fa-trash"></i></button>
										</form>
									</div>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function(){
			$('table').DataTable({
				'bLengthChange': false,
				'searching': false,
			});
		});
	</script>
@endsection

resources/views/criteria/show.blade.php
@extends('layout')

@section('title','Data Criteria')

@section('content')
	<div class="container">
		<div class="card">
			<form action="{{ route('criteria.update',$criteria->id) }}" method="post">
				@csrf
				@method('put')				
				<div class="card-header">
					<h1 class="card-title">Data Criteria</h1>
				</div>
				<div class="card-body">
					<div class="form-group">
						<label>Nama</label>
						<input type="text" class="form-control" name="name" placeholder="Nama" value="{{ $criteria->name }}" required>
						@if($errors->has('name'))
							<p class="alert alert-warning">{{ $errors->first('name') }}</p>
						@endif
					</div>
					<div class="form-group">
						<label>Bobot</label>
						<input type="text" class="form-control" name="weight" placeholder="Nilai Bobot" value="{{ $criteria->weight }}" required>
						@if($errors->has('weight'))
							<p class="alert alert-warning">{{ $errors->first('weight') }}</p>
						@endif
					</div>
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-outline-primary pull-right">Simpan</button>
				</div>
			</form>
		</div>
	</div>
@endsection