routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function(){
	return redirect()->route('criteria.index');
});

Route::prefix('alternative')->name('alternative.')->group(function(){
	Route::get('', 'AlternativeController@index')->name('index');
	Route::get('create', 'AlternativeController@create')->name('create');
	Route::post('', 'AlternativeController@store')->name('store');
	Route::get('{alternative}', 'AlternativeController@show')->name('show');
	Route::put('{alternative}', 'AlternativeController@update')->name('update');
	Route::delete('{alternative}', 'AlternativeController@destroy')->name('destroy');
});

Route::prefix('criteria')->name('criteria.')->group(function(){
	Route::get('', 'CriteriaController@index')->name('index');
	Route::get('create', 'CriteriaController@create')->name('create');
	Route::post('', 'CriteriaController@store')->name('store');
	Route::get('{criteria}', 'CriteriaController@show')->name('show');
	Route::put('{criteria}', 'CriteriaController@update')->name('update');
	Route::delete('{criteria}', 'CriteriaController@destroy')->name('destroy');
});

Route::prefix('score')->name('score.')->group(function(){
	Route::get('', 'ScoreController@index')->name('index');
	Route::get('create', 'ScoreController@create')->name('create');
	Route::post('', 'ScoreController@store')->name('store');
	Route::get('{alternative}', 'ScoreController@show')->name('show');
	Route::put('{alternative}', 'ScoreController@update')->name('update');
	Route::delete('{alternative}', 'ScoreController@destroy')->name('destroy');
});

Route::prefix('scoring')->name('scoring.')->group(function(){
	Route::get('', 'ScoringController@index')->name('index');
});

app/Score.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Score extends Model
{
    protected $fillable = [
    	'alternative_id', 'criteria_id', 'score',
    ];

    public function alternative()
    {
    	return $this->belongsTo('App\Alternative');
    }

    public function criteria()
    {
    	return $this->belongsTo('App\Criteria');
    }
}

app/Http/Controllers/ScoreController.php
<?php

namespace App\Http\Controllers;

use App\Score;
use App\Alternative;
use App\Criteria;
use Illuminate\Http\Request;

class ScoreController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('score.index')->with([
            'criterias' => Criteria::all(),
            'alternatives' => Alternative::orWhere('name','LIKE','%'.request('q').'%')->has('scores')->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('score.create')->with([
            'alternatives' => Alternative::doesntHave('scores')->get(),
            'criterias' => Criteria::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $alternative = Alternative::find($request->alternative_id);

        $criterias = Criteria::all();

        foreach ($criterias as $key => $criteria) {
            $criteria_id = 'criteria_'.$criteria->id;
            $criteria_score = 'score_'.$key;

            $this->validate($request, [
                $criteria_score => 'required|integer|max:5',
            ]);

            $alternative->scores()->create([
                'criteria_id' => $request->$criteria_id,
                'score' => $request->$criteria_score,
            ]);
        }

        return redirect()->route('score.index')->with('info','Penilaian Berhasil ditambahkan');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Score  $score
     * @return \Illuminate\Http\Response
     */
    public function show(Alternative $alternative)
    {
        return view('score.show')->with([
            'scores' => Score::where('alternative_id',$alternative->id)->orderBy('criteria_id')->get(),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Score  $score
     * @return \Illuminate\Http\Response
     */
    public function edit(Score $score)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Score  $score
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Alternative $alternative)
    {
        $scores = Score::where('alternative_id',$alternative->id)->orderBy('criteria_id')->get();

        foreach ($scores as $key => $score) {
            $criteria_score = 'score_'.$key;

            $this->validate($request, [
                $criteria_score => 'required|integer|max:5',
            ]);

            $score->update([
                'score' => $request->$criteria_score,
            ]);
        }

        return redirect()->route('score.index')->with('info','Penilaian berhasil diperbaharui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Score  $score
     * @return \Illuminate\Http\Response
     */
    public function destroy(ALternative $alternative)
    {
        Score::where('alternative_id',$alternative->id)->delete();

        return redirect()->route('score.index')->with('info','Penilaian berhasil dihapus');
    }
}

resources/views/score/create.blade.php
@extends('layout')

@section('title','Tambah Penilaian')

@section('content')
	<div class="container">
		<div class="card">
			<form action="{{ route('score.store') }}" method="post">
				@csrf
				<div class="card-header">
					<h1 class="card-title">Tambah Penilaian</h1>
				</div>
				<div class="card-body">
					<div class="form-group">
						<label>Nama Alternatif</label>
						<select name="alternative_id" class="form-control">
							<option hidden>Nama Alternatif</option>
							@foreach($alternatives as $alternative)
							<option value="{{ $alternative->id }}">{{ $alternative->name }}</option>
							@endforeach
						</select>
					</div>
					@foreach($criterias as $key => $criteria)
						<div class="form-group">
							<label>{{ $criteria->name }}</label>
							<input type="hidden" name="criteria_{{ $criteria->id }}" value="{{ $criteria->id }}">
							<input type="number" class="form-control" name="score_{{ $key }}" placeholder="Nilai (1-5)" required>
							@if($errors->has("score_$key"))
								<p class="alert alert-warning">{{ $errors->first("score_$key") }}</p>
							@endif
						</div>
					@endforeach
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-outline-primary pull-right">Simpan</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/score/index.blade.php
@extends('layout')

@section('title','Penilaian')

@section('content')
	<div class="card">
		<div class="card-header">
			<h1 class="card-title">Data Penilaian</h1>
			<form action="{{ route('score.index') }}" method="GET">
				<div class="input-group">
					<input type="search" class="form-control" placeholder="Cari data penilaian..." name="q" value="{{ request('q') }}">
					<div class="input-group-append">
						<button type="submit" class="btn btn-outline-secondary"><i class="fa fa-search"></i></button>
						&nbsp
						<a href="{{ route('score.create') }}" class="btn btn-outline-primary"><i class="fa fa-plus"></i></a>
					</div>
				</div>
			</form>
		</div>
		<div class="card-body">
			@if(session()->has('info'))
				<p class="alert alert-success">{{ session()->get('info') }}</p>
			@endif
			<div class="table-responsive">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th width="1%">#</th>
							<th>Nama</th>
							@foreach($criterias as $criteria)
							<th>{{ $criteria->name }}</th>
							@endforeach
							<th width="5%">Aksi</th>
						</tr>
					</thead>
					<tbody>
						@foreach($alternatives as $key => $alternative)
							<tr>
								<td class="text-right">{{ $key+1 }}</td>
								<td>{{ $alternative->name }}</td>
								@foreach($alternative->scores as $score)
									<td>{{ $score->score }}</td>
								@endforeach
								<td>
									<div class="btn-group">
										<a href="{{ route('score.show',$alternative->id) }}" class="btn btn-outline-success"><i class="fa fa-eye"></i></a>
										&nbsp
										<form id="delete" action="{{ route('score.destroy',$alternative->id) }}" method="post">
										@csrf
										@method('delete')
										<button type="submit" href="#" class="btn btn-outline-danger" onclick="return confirm('Hapus penilaian {{ $alternative->name }}')"><i class="fa fa-trash"></i></button>
										</form>
									</div>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function(){
			$('table').DataTable({
				'bLengthChange': false,
				'searching': false,
			});
		});
	</script>
@endsection

resources/views/score/show.blade.php
@extends('layout')

@section('title','Data Penilaian')

@section('content')
	<div class="container">
		<div class="card">
			<form action="{{ route('score.update',$scores->first()->alternative->id )}}" method="post">
				@csrf
				@method('put')				
				<div class="card-header">
					<h1 class="card-title">Data Penilaian</h1>
				</div>
				<div class="card-body">
					<div class="form-group">
						<label>Nama</label>
						<input type="text" class="form-control" name="name" placeholder="Nama" value="{{ $scores->first()->alternative->name }}" disabled>
					</div>
					@foreach($scores as $key => $score)
						<div class="form-group">
							<label>{{ $score->criteria->name }}</label>
							<input type="number" class="form-control" name="score_{{ $key }}" placeholder="Nilai" value="{{ $score->score }}" required>
							@if($errors->has("score_$key"))
								<p class="alert alert-warning">{{ $errors->first("score_$key") }}</p>
							@endif
						</div>
					@endforeach
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-outline-primary pull-right">Simpan</button>
				</div>
			</form>
		</div>
	</div>
@endsection