routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function(){
	return redirect()->route('criteria.index');
});

Route::prefix('alternative')->name('alternative.')->group(function(){
	Route::get('', 'AlternativeController@index')->name('index');
	Route::get('create', 'AlternativeController@create')->name('create');
	Route::post('', 'AlternativeController@store')->name('store');
	Route::get('{alternative}', 'AlternativeController@show')->name('show');
	Route::put('{alternative}', 'AlternativeController@update')->name('update');
	Route::delete('{alternative}', 'AlternativeController@destroy')->name('destroy');
});

Route::prefix('criteria')->name('criteria.')->group(function(){
	Route::get('', 'CriteriaController@index')->name('index');
	Route::get('create', 'CriteriaController@create')->name('create');
	Route::post('', 'CriteriaController@store')->name('store');
	Route::get('{criteria}', 'CriteriaController@show')->name('show');
	Route::put('{criteria}', 'CriteriaController@update')->name('update');
	Route::delete('{criteria}', 'CriteriaController@destroy')->name('destroy');
});

Route::prefix('score')->name('score.')->group(function(){
	Route::get('', 'ScoreController@index')->name('index');
	Route::get('create', 'ScoreController@create')->name('create');
	Route::post('', 'ScoreController@store')->name('store');
	Route::get('{alternative}', 'ScoreController@show')->name('show');
	Route::put('{alternative}', 'ScoreController@update')->name('update');
	Route::delete('{alternative}', 'ScoreController@destroy')->name('destroy');
});

Route::prefix('scoring')->name('scoring.')->group(function(){
	Route::get('', 'ScoringController@index')->name('index');
});

app/Alternative.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alternative extends Model
{
    protected $fillable = [
    	'name', 'phone_number', 'address',
    ];

    public function scores()
    {
    	return $this->hasMany('App\Score')->orderBy('criteria_id','ASC');
    }

}

app/Http/Controllers/AlternativeController.php
<?php

namespace App\Http\Controllers;

use App\Alternative;
use Illuminate\Http\Request;

class AlternativeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // return view('alternative.index')->with([
        //     'alternatives' => Alternative::orWhere('name','LIKE','%'.request('q').'%')->orWhere('phone_number','LIKE','%'.request('q').'%')->orWhere('address','LIKE','%'.request('q').'%')->orderBy('id','DESC')->paginate(10)->appends(['q'=>request('q')]),
        // ]);

        return view('alternative.index')->with([
            'alternatives' => Alternative::orWhere('name','LIKE','%'.request('q').'%')->orWhere('phone_number','LIKE','%'.request('q').'%')->orWhere('address','LIKE','%'.request('q').'%')->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('alternative.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'phone_number' => 'required|numeric',
            'address' => 'required',
        ]);

        Alternative::create([
            'name' => $request->name,
            'phone_number' => $request->phone_number,
            'address' => $request->address,
        ]);

        return redirect()->route('alternative.index')->with('info','Alternatif berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Alternative  $alternative
     * @return \Illuminate\Http\Response
     */
    public function show(Alternative $alternative)
    {
        return view('alternative.show')->with('alternative',$alternative);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Alternative  $alternative
     * @return \Illuminate\Http\Response
     */
    public function edit(Alternative $alternative)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Alternative  $alternative
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Alternative $alternative)
    {
        $this->validate($request, [
            'name' => 'required',
            'phone_number' => 'required|numeric',
            'address' => 'required',
        ]);

        $alternative->update([
            'name' => $request->name,
            'phone_number' => $request->phone_number,
            'address' => $request->address,
        ]);

        return redirect()->route('alternative.index')->with('info','Alternatif berhasil diperbaharui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Alternative  $alternative
     * @return \Illuminate\Http\Response
     */
    public function destroy(Alternative $alternative)
    {
        $alternative->delete();

        return redirect()->route('alternative.index')->with('info','Alternatif berhasil dihapus');
    }
}

resources/views/alternative/create.blade.php
@extends('layout')

@section('title','Tambah Alternatif')

@section('content')
	<div class="container">
		<div class="card">
			<form action="{{ route('alternative.store') }}" method="post">
				@csrf
				<div class="card-header">
					<h1 class="card-title">Tambah Alternatif</h1>
				</div>
				<div class="card-body">
					<div class="form-group">
						<label>Nama</label>
						<input type="text" class="form-control" name="name" placeholder="Nama" required>
						@if($errors->has('name'))
							<p class="alert alert-warning">{{ $errors->first('name') }}</p>
						@endif
					</div>
					<div class="form-group">
						<label>No HP</label>
						<input type="text" class="form-control" name="phone_number" placeholder="No HP" required>
						@if($errors->has('phone_number'))
							<p class="alert alert-warning">{{ $errors->first('phone_number') }}</p>
						@endif
					</div>
					<div class="form-group">
						<label>Alamat</label>
						<textarea class="form-control" name="address" placeholder="Alamat" style="height: 150px" required></textarea>
						@if($errors->has('address'))
							<p class="alert alert-warning">{{ $errors->first('address') }}</p>
						@endif
					</div>
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-outline-primary pull-right">Simpan</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/alternative/index.blade.php
@extends('layout')

@section('title','Alternatif')

@section('content')
	<div class="card">
		<div class="card-header">
			<h1 class="card-title">Data Alternatif</h1>
			<form action="{{ route('alternative.index') }}" method="GET">
				<div class="input-group">
					<input type="search" class="form-control" placeholder="Cari data alternatif..." name="q" value="{{ request('q') }}">
					<div class="input-group-append">
						<button type="submit" class="btn btn-outline-secondary"><i class="fa fa-search"></i></button>
						&nbsp
						<a href="{{ route('alternative.create') }}" class="btn btn-outline-primary"><i class="fa fa-plus"></i></a>
					</div>
				</div>
			</form>
		</div>
		<div class="card-body">
			@if(session()->has('info'))
				<p class="alert alert-success">{{ session()->get('info') }}</p>
			@endif
			<div class="table-responsive">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th width="1%">#</th>
							<th>Nama</th>
							<th>No HP</th>
							<th>Alamat</th>
							<th width="5%">Aksi</th>
						</tr>
					</thead>
					<tbody>
						@foreach($alternatives as $key => $alternative)
							<tr>
								<td class="text-right">{{ $key+1 }}</td>
								<td>{{ $alternative->name }}</td>
								<td>{{ $alternative->phone_number }}</td>
								<td>{{ $alternative->address }}</td>
								<td>
									<div class="btn-group">
										<a href="{{ route('alternative.show',$alternative->id) }}" class="btn btn-outline-success"><i class="fa fa-eye"></i></a>
										&nbsp
										<form id="delete" action="{{ route('alternative.destroy',$alternative->id)}}" method="post">
										@csrf
										@method('delete')
										<button type="submit" href="#" class="btn btn-outline-danger" onclick="return confirm('Hapus alternatif {{ $alternative->name }}')"><i class="fa fa-trash"></i></button>
										</form>
									</div>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function(){
			$('table').DataTable({
				'bLengthChange': false,
				'searching': false,
			});
		})
	</script>
@endsection

resources/views/alternative/show.blade.php
@extends('layout')

@section('title','Data Alternatif')

@section('content')
	<div class="container">
		<div class="card">
			<form action="{{ route('alternative.update',$alternative->id) }}" method="post">
				@csrf
				@method('put')				
				<div class="card-header">
					<h1 class="card-title">Data Alternatif</h1>
				</div>
				<div class="card-body">
					<div class="form-group">
						<label>Nama</label>
						<input type="text" class="form-control" name="name" placeholder="Nama" value="{{ $alternative->name }}" required>
						@if($errors->has('name'))
							<p class="alert alert-warning">{{ $errors->first('name') }}</p>
						@endif
					</div>
					<div class="form-group">
						<label>No HP</label>
						<input type="text" class="form-control" name="phone_number" placeholder="No HP" value="{{ $alternative->phone_number }}" required>
						@if($errors->has('phone_number'))
							<p class="alert alert-warning">{{ $errors->first('phone_number') }}</p>
						@endif
					</div>
					<div class="form-group">
						<label>Alamat</label>
						<textarea class="form-control" name="address" placeholder="Alamat" style="height: 150px" required>{{ $alternative->address }}</textarea>
						@if($errors->has('address'))
							<p class="alert alert-warning">{{ $errors->first('address') }}</p>
						@endif
					</div>
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-outline-primary pull-right">Simpan</button>
				</div>
			</form>
		</div>
	</div>
@endsection